openapi: 3.0.0
info:
  title: Book API
  version: 1.0.0
servers:
- url: http://localhost:5000
- url: http://2526-ii-int-3505-1-gpf3-2g8bjq0ny-dinhhoccodes-projects.vercel.app
paths:
  /api/v1/books:
    get:
      operationId: api_v1_books_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookListResponse"
          description: Lấy danh sách sách thành công
      summary: Lấy danh sách sách
      x-openapi-router-controller: OpenAPISpec.controllers.default_controller
    post:
      operationId: api_v1_books_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
          description: Tạo sách thành công
      summary: Tạo sách mới
      x-openapi-router-controller: OpenAPISpec.controllers.default_controller
  /api/v1/books/search:
    get:
      operationId: api_v1_books_search_get
      parameters:
      - description: Tìm kiếm theo tiêu đề sách
        explode: true
        in: query
        name: title
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookListResponse"
          description: Tìm kiếm sách thành công
      summary: Tìm kiếm sách
      x-openapi-router-controller: OpenAPISpec.controllers.default_controller
  /api/v1/books/{book_id}:
    delete:
      operationId: api_v1_books_book_id_delete
      parameters:
      - explode: false
        in: path
        name: book_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          description: Xóa sách thành công
      summary: Xóa sách
      x-openapi-router-controller: OpenAPISpec.controllers.default_controller
    get:
      operationId: api_v1_books_book_id_get
      parameters:
      - explode: false
        in: path
        name: book_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
          description: Lấy thông tin sách thành công
        "404":
          description: không tìm thấy sách
      summary: Lấy thông tin sách theo id
      x-openapi-router-controller: OpenAPISpec.controllers.default_controller
    patch:
      operationId: api_v1_books_book_id_patch
      parameters:
      - explode: false
        in: path
        name: book_id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
          description: Cập nhật thành công
        "404":
          description: Không tìm thấy sách
      summary: Cập nhật một phần sách
      x-openapi-router-controller: OpenAPISpec.controllers.default_controller
    put:
      operationId: api_v1_books_book_id_put
      parameters:
      - explode: false
        in: path
        name: book_id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
          description: Cập nhật thông tin sách thành công
        "404":
          description: không tìm thấy sách
      summary: Cập nhật thông tin sách
      x-openapi-router-controller: OpenAPISpec.controllers.default_controller
components:
  schemas:
    Book:
      example:
        published_year: 6
        author: author
        price: 1.4658129
        genre: genre
        id: 0
        title: title
        is_available: true
      properties:
        id:
          title: id
          type: integer
        title:
          title: title
          type: string
        author:
          title: author
          type: string
        genre:
          title: genre
          type: string
        published_year:
          title: published_year
          type: integer
        price:
          format: float
          title: price
          type: number
        is_available:
          title: is_available
          type: boolean
      title: Book
      type: object
    CreateBookRequest:
      example:
        published_year: 0
        author: author
        price: 6.027456183070403
        genre: genre
        title: title
        is_available: true
      properties:
        title:
          title: title
          type: string
        author:
          title: author
          type: string
        genre:
          title: genre
          type: string
        published_year:
          title: published_year
          type: integer
        price:
          title: price
          type: number
        is_available:
          title: is_available
          type: boolean
      title: CreateBookRequest
      type: object
    BookResponse:
      example:
        data:
          published_year: 6
          author: author
          price: 1.4658129
          genre: genre
          id: 0
          title: title
          is_available: true
        success: true
        message: message
      properties:
        success:
          title: success
          type: boolean
        data:
          $ref: "#/components/schemas/Book"
        message:
          title: message
          type: string
      title: BookResponse
      type: object
    BookListResponse:
      example:
        data:
        - published_year: 6
          author: author
          price: 1.4658129
          genre: genre
          id: 0
          title: title
          is_available: true
        - published_year: 6
          author: author
          price: 1.4658129
          genre: genre
          id: 0
          title: title
          is_available: true
        success: true
        message: message
      properties:
        success:
          title: success
          type: boolean
        data:
          items:
            $ref: "#/components/schemas/Book"
          title: data
          type: array
        message:
          title: message
          type: string
      title: BookListResponse
      type: object
